# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://wanjinhu.github.io
date_format: "ordinal"
title: Wanjin Hu (胡万金)
subtitle: "思考人生，探索世界，知行合一"
description: "There is only one heroism in the world: to see the world as it is and to love it. (世界上只有一种真正的英雄主义，那就是认清生活真相后依旧热爱生活。)"
keywords: Wanjin Hu, Blog
timezone: Asia/Shanghai
encoding: "utf-8"
# 页面左下角显示的年份
since: 2023
# 源码仓库，请替换成自己的
repository: wanjinhu/wanjinhu.github.io
# 对 css 和 js 资源的 cdn 加速配置
cdn:
    jsdelivr:
        enabled: false
# 可选组件配置
components:
    # My Popular Repositories
    side_bar_repo:
        enabled: true
        limit: 5
    # 文章字数统计
    word_count:
        enabled: true
    # 页面右上角，以及「关于」页面的二维码
    # 修改图片请替换 assets/images/qrcode.jpg
    qrcode:
        enabled: true
        image_alt: Wanjin Hu (胡万金)
    # 维基索引页使用哪种视图，支持 列表（list）/分类（cate）
    wiki:
        view: cate
    # 图片灯箱效果功能
    fancybox:
        enabled: false
# 压缩页面内容
compress_html:
  clippings: all
  comments: ["<!--", "-->"]
# 代码高亮风格，支持的 theme 列表见 https://github.com/mzlogin/rouge-themes
highlight_theme: github

# ---------------- #
#      Author      #
# ---------------- #
author: Wanjin Hu (胡万金)
organization: 
organization_url: 
github_username: wanjinhu
location: Shanghai, China
email: wanjin.hu@outlook.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /archives/
    label: 归档
    mobile-hidden: true

  -
    href: /open-source/
    label: 开源
    mobile-hidden: true

  # -
    # href: /fragments/
    # label: 片段

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接
    mobile-hidden: true

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 10
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
plugins:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/
    fragments:
        output: true
        permalink: /fragment/:path/

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk, utterances, beaudar, giscus
comments_provider: giscus
# !!! 重要!!! 修改下面这些信息为你自己申请的
# disqus 配置参考：https://disqus.com
# disqus:
#     username: 
# gitment 配置参考：https://imsun.net/posts/gitment-introduction/
# gitment:
#     owner: mzlogin
#     repo: blog-comments
#     oauth:
#         client_id: d2e1cbbd298958076462
#         client_secret: b42a4178e5fd4a7cf63189ef4b1453b05c375709
# gitalk 配置参考：https://github.com/gitalk/gitalk#install
# gitalk:
#     owner: mzlogin
#     repo: blog-comments
#     clientID: d2e1cbbd298958076462
#     clientSecret: b42a4178e5fd4a7cf63189ef4b1453b05c375709
# utterances 配置参考：https://utteranc.es/
# utterances:
#     repo: mzlogin/blog-comments
# beaudar 配置参考：https://beaudar.lipk.org/
# beaudar:
#     repo: mzlogin/blog-comments
# giscus 配置参考：https://giscus.app/zh-CN
giscus:
    repo: wanjinhu/wanjinhu.github.io
    repo-id: R_kgDOKJb3gA
    category: Announcements
    category-id: DIC_kwDOKJb3gM4CYvQX
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: true
    # 最多显示多少条搜索结果
    limit: 10

# ---------------- #
#      Google      #
# ---------------- #
# google:
#     analytics_id: # G-20FLEG5Q2W
#     adsense:
#         enabled: false
#         footer: false
#         sidebar: false
#         sidebar-detail: false
#         content_header: false
#         content_footer: false
